send_command:
  name: Send Command
  description: Send command to Naim NDX
  target:
    entity:
      integration: naim_ndx
      domain: media_player
  fields:
    command:
      name: Command
      description: 'The Command to send to the device.'
      required: true
      selector:
        select:
          multiple: false
          options:
            - disp
            - one
            - two
            - three
            - four
            - five
            - six
            - seven
            - eight
            - nine
            - zero
            - preset
            - store
            - vol+
            - vol-
            - mute
            - ok
            - up
            - down
            - left
            - right
            - exit
            - repeat
            - shuffle
            - setup
            - info
            - play
            - previous
            - next
            - stop
            - rewind
            - fastforward
            - cd
            - radio
            - pc
            - ipod
            - tv
            - av
            - hdd
            - aux
